pipeline {

    agent none

    environment {
        CI = 'true'
    }

    stages {

        stage('Build Linux Packages') {

            agent {
                label 'linux'
            }

            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){
                    sh 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun && git stash && git pull origin master && make clean config build-linux'
                    sh 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun && git stash && git pull origin master && make config build-arm'
                    sh 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun && git stash && git pull origin master && make config build-darwin'
                    sh 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun && git stash && git pull origin master && make config build-win'

                   sh label: 'copy-configs', script: 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun && cp ../../../framework/LICENSE bin && cat ../../../framework/NOTICE NOTICE > bin/NOTICE'

                   sh label: 'package-linux-amd64', script: 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun/bin && tar cfz ${WORKSPACE}/loadrun-$VERSION-$BUILD_NUMBER-linux-amd64.tar.gz loadrun-linux-amd64 loadrun.yml LICENSE NOTICE'
                   sh label: 'package-linux-386', script: 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun/bin && tar cfz ${WORKSPACE}/loadrun-$VERSION-$BUILD_NUMBER-linux-386.tar.gz loadrun-linux-386 loadrun.yml LICENSE NOTICE'
                   sh label: 'package-linux-mips', script: 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun/bin && tar cfz ${WORKSPACE}/loadrun-$VERSION-$BUILD_NUMBER-linux-mips.tar.gz loadrun-linux-mips loadrun.yml LICENSE NOTICE'
                   sh label: 'package-linux-mipsle', script: 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun/bin && tar cfz ${WORKSPACE}/loadrun-$VERSION-$BUILD_NUMBER-linux-mipsle.tar.gz loadrun-linux-mipsle loadrun.yml LICENSE NOTICE'
                   sh label: 'package-linux-mips64', script: 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun/bin && tar cfz ${WORKSPACE}/loadrun-$VERSION-$BUILD_NUMBER-linux-mips64.tar.gz loadrun-linux-mips64 loadrun.yml LICENSE NOTICE'
                   sh label: 'package-linux-mips64le', script: 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun/bin && tar cfz ${WORKSPACE}/loadrun-$VERSION-$BUILD_NUMBER-linux-mips64le.tar.gz loadrun-linux-mips64le loadrun.yml LICENSE NOTICE'
                   sh label: 'package-linux-arm5', script: 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun/bin && tar cfz ${WORKSPACE}/loadrun-$VERSION-$BUILD_NUMBER-linux-arm5.tar.gz loadrun-linux-armv5 loadrun.yml LICENSE NOTICE'
                   sh label: 'package-linux-arm6', script: 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun/bin && tar cfz ${WORKSPACE}/loadrun-$VERSION-$BUILD_NUMBER-linux-arm6.tar.gz loadrun-linux-armv6 loadrun.yml LICENSE NOTICE'
                   sh label: 'package-linux-arm7', script: 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun/bin && tar cfz ${WORKSPACE}/loadrun-$VERSION-$BUILD_NUMBER-linux-arm7.tar.gz loadrun-linux-armv7 loadrun.yml LICENSE NOTICE'
                   sh label: 'package-linux-arm64', script: 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun/bin && tar cfz ${WORKSPACE}/loadrun-$VERSION-$BUILD_NUMBER-linux-arm64.tar.gz loadrun-linux-arm64 loadrun.yml LICENSE NOTICE'

                    sh label: 'package-mac-amd64', script: 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun/bin && zip -r ${WORKSPACE}/loadrun-$VERSION-$BUILD_NUMBER-mac-amd64.zip loadrun-mac-amd64 loadrun.yml LICENSE NOTICE'
                    sh label: 'package-mac-arm64', script: 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun/bin && zip -r ${WORKSPACE}/loadrun-$VERSION-$BUILD_NUMBER-mac-arm64.zip loadrun-mac-arm64 loadrun.yml LICENSE NOTICE'

                    sh label: 'package-win-amd64', script: 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun/bin && zip -r ${WORKSPACE}/loadrun-$VERSION-$BUILD_NUMBER-windows-amd64.zip loadrun-windows-amd64.exe loadrun.yml LICENSE NOTICE'
                    sh label: 'package-win-386', script: 'cd /home/jenkins/go/src/infini.sh/loadgen/cmd/loadrun/bin && zip -r ${WORKSPACE}/loadrun-$VERSION-$BUILD_NUMBER-windows-386.zip loadrun-windows-386.exe loadrun.yml LICENSE NOTICE'


                    fingerprint 'loadrun-$VERSION-$BUILD_NUMBER-*'
                    archiveArtifacts artifacts: 'loadrun-$VERSION-$BUILD_NUMBER-*', fingerprint: true, followSymlinks: true, onlyIfSuccessful: true
                }
            }
        }

    }
}
